# Generated by Django 3.2.4 on 2021-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=60)),
                ('stateCode', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
